package karel.interpreter;

public enum Test { 	FRONT_IS_CLEAR, FRONT_IS_BLOCKED, LEFT_IS_CLEAR, LEFT_IS_BLOCKED, RIGHT_IS_CLEAR, RIGHT_IS_BLOCKED,
					NEXT_TO_A_BEEPER, NOT_NEXT_TO_A_BEEPER, ANY_BEEPERS_IN_BEEPER_BAG, NO_BEEPERS_IN_BEEPER_BAG, FACING_NORTH, NOT_FACING_NORTH,
					FACING_SOUTH, NOT_FACING_SOUTH, FACING_EAST, NOT_FACING_EAST, FACING_WEST, NOT_FACING_WEST }
